### ISSUE TITLE
Global install really necessary?

### ISSUE THREAD

**Issue by istvank** [y-js/y-websockets-server#4]
In the README you install the y-websockets-server globally. Is that really necessary?

**Comment by Joeao** [comment]
It isn't necessary. Well.. I'm not doing it and it works fine.
You should make a pull request.

**Comment by istvank** [comment]
Good idea, @DadaMonad should focus on the important things! :smile:

**Comment by dmonad** [comment]
I updated the docu and improved the overall adopting process (I hope). I always wanted to write a heroku guide - so I just did it.

This was 10 percent code, 10 percent debugging, and 80 percent finding out how indentation in Markdown works -.-

@istvank I'm awaiting your pull request on docker images :)

**Comment by istvank** [comment]
Here you go! :whale:
