### ISSUE TITLE
Logging Improvements

### ISSUE THREAD

**Issue by nicolaescu** [y-js/y-websockets-server#7]
Would be great to add as soon as possible a better logging mechamism for this.
Starting the websockets server Docker container, the only available console log output is of the form User X joins room: Y. 
I would like to have also the timestamp included, or a better solution to log all messages. It is very important here that we have a location where the log file is stored and can be checked, regardless of the option taked for starting the Websocketsserver.

**Comment by nicolaescu** [comment]
As a further step, we should also be able to log other information - upon request, let's say a flag when starting the server - like the nature of messages sent and received through a room, user which sends the info, etc.

**Comment by dmonad** [comment]
I opted for [debug](https://github.com/visionmedia/debug) as a logging utility. I am now able to define namespaces like `y:transformation`, `y:connector`, and `y:websockets-server`. You can selectively select to which logging messages (published under a specific namespace) you want to listen to.

For example, the following flag currently makes a lot of sense:
```
DEBUG=y*,-y:connector-message y-websockets-server --port 1234
```

There is also a nice way to write the log to a file. This was already possible, but contains timestamps now:
```sh
DEBUG_COLORS=0 DEBUG=y*,-y:connector-message y-websockets-server --port 1234 > log.txt
```

I already published the changes. Please use this thread if you are interested in any specific logging outputs. Over time the amount of logging messages will grow. So you should only use the namespaces you are really interested in.
