### ISSUE TITLE
npm i --save y-websockets-server fails due to dependency version conflict

### ISSUE THREAD

**Issue by f-ohler** [y-js/y-websockets-server#8]
Currently, the npm install command fails with the message
`UNMET PEER DEPENDENCY yjs@12.1.4`
which is (as I see it) caused by the optional leveldb dependency which is optionally required in version 0.0.0, but yjs 12 is only compatible with leveldb 0.0.1
`y-leveldb@0.0.0 requires a peer of yjs@^11.0.0 && >=11.2.4 but none was installed.`

Workaround: install via
`npm i --save y-websockets-server --no-optional`

**Comment by dmonad** [comment]
Thanks for reporting this. I removed the optional leveldb dependency. This should be fixed in 9.1.6
